-- UI users (separate from agent API keys)
CREATE TABLE app_users (
    id            SERIAL      PRIMARY KEY,
    username      TEXT        NOT NULL UNIQUE,
    email         TEXT        NOT NULL UNIQUE,
    full_name     TEXT,
    password_hash TEXT        NOT NULL,
    role          TEXT        NOT NULL DEFAULT 'viewer'
                              CHECK (role IN ('admin', 'analyst', 'viewer')),
    active        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login    TIMESTAMPTZ
);

-- Default admin account — password: Admin@123456 (BCrypt hash, work factor 10)
-- Generated by BCrypt.Net: BCrypt.HashPassword("Admin@123456", 10)
INSERT INTO app_users (username, email, full_name, password_hash, role)
VALUES (
    'admin',
    'admin@localhost',
    'System Administrator',
    '$2a$10$hjMtIKT/cE2xMXdYjJAnCOUBbe4jJYk1Cs7Uq0iEH8fJZkhQVW/w6',
    'admin'
) ON CONFLICT DO NOTHING;
